/* PROCEDURES 
SP_STORAGE PROCEDURE */

USE EMPRESA;
GO

/* CRIAÇÃO DAS TABELAS */
DROP TABLE TB_PESSOAS
GO

CREATE TABLE TB_PESSOAS(
	IDPESSOA INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(30) NOT NULL,
	SEXO CHAR(1) NOT NULL CHECK (SEXO IN('F','M')),
	NASCIMENTO DATE NOT NULL, 
);
GO

DROP TABLE TB_TELEFONE 
GO

CREATE TABLE TB_TELEFONE(
	IDTELEFONE INT NOT NULL IDENTITY,
	TIPO CHAR(3) NOT NULL CHECK (TIPO IN('CEL','COM')),
	NUMERO CHAR(10) NOT NULL,
	ID_PESSOA INT
);

/* FOREING KEY */
ALTER TABLE TB_TELEFONE ADD CONSTRAINT FK_PESSOA 
FOREIGN KEY (ID_PESSOA) REFERENCES TB_PESSOAS(IDPESSOA);
GO

/* SELECT DE VERIFICAÇÃO */
SELECT * FROM TB_PESSOAS
GO

SELECT * FROM TB_TELEFONE
GO

/* INSERTS */
INSERT INTO TB_PESSOAS VALUES 
('ANA','F','2001/12/10'),
('JUNIOR','M','1998/08/06'),
('THAIS','F','2005/04/21');
GO

INSERT INTO TB_TELEFONE VALUES 
('CEL','1654920354',1),
('CEL','2031564789',2),
('COM','3026947411',1),
('CEL','7451394512',3),
('COM','8544612345',2),
('COM','9541354120',3);
GO

/* INNER JOIN  */
SELECT TB_PESSOAS.IDPESSOA, TB_PESSOAS.NOME, TB_TELEFONE.NUMERO, TB_TELEFONE.TIPO 
FROM TB_PESSOAS INNER JOIN TB_TELEFONE ON TB_PESSOAS.IDPESSOA = TB_TELEFONE.ID_PESSOA
WHERE TB_TELEFONE.TIPO = 'COM'
GO

/* PROCEDURE COM PARAMETROS */
DROP PROC CONTA
GO

CREATE PROC CONTA
@@NUM1 INT,
@@NUM2 INT

AS
	SELECT (@@NUM1+@@NUM2) AS RESULTADO
GO

EXEC CONTA 1,1 
GO

/* PROCEDURES EM TABELAS */
DROP PROC PROC_BUSCA_CEL_COMERCIAL
GO

CREATE PROC PROC_BUSCA_CEL_COMERCIAL
AS
	SELECT TB_PESSOAS.IDPESSOA, TB_PESSOAS.NOME, TB_TELEFONE.NUMERO, TB_TELEFONE.TIPO 
	FROM TB_PESSOAS INNER JOIN TB_TELEFONE ON TB_PESSOAS.IDPESSOA = TB_TELEFONE.ID_PESSOA
	WHERE TB_TELEFONE.TIPO = 'COM'
GO

EXEC PROC_BUSCA_CEL_COMERCIAL
GO

/* TRAZER TELEFONES DE ACORDO COM O TIPO PASSADO */
DROP PROC PROC_TELEFONES
GO

CREATE PROC PROC_TELEFONES 
	@TIPO CHAR(3)
AS
	SELECT TB_PESSOAS.NOME, TB_TELEFONE.NUMERO
	FROM TB_PESSOAS INNER JOIN TB_TELEFONE ON IDPESSOA = ID_PESSOA 
	WHERE TIPO = @TIPO
GO

EXEC PROC_TELEFONES 'CEL' 
GO

/* PARAMETROS DE OUTPUT -> SAÍDA .... E INPUT -> ENTRADA */

SELECT TIPO, COUNT(*) AS QTDE
FROM TB_TELEFONE
GROUP BY TIPO
GO

/* PROCEDURE */
DROP PROC PROC_GETTIPO
GO

CREATE PROC PROC_GETTIPO
@TIPO CHAR(3), @CONTADOR INT OUTPUT
AS
	SELECT @CONTADOR = COUNT(*) 
	FROM TB_TELEFONE 
	WHERE TIPO = @TIPO
GO

/* 1º E 2º MANEIRA */
DECLARE @SAIDA INT /* PRINT */
EXEC PROC_GETTIPO @TIPO = 'CEL', @CONTADOR = @SAIDA OUTPUT
SELECT @SAIDA
GO

DECLARE @SAIDA INT 
EXEC PROC_GETTIPO 'CEL', @SAIDA OUTPUT
SELECT @SAIDA
GO

/* PROCEDURE DE CADASTRO (DO MVC -> MC)*/
DROP PROC PROC_CADASTRO
GO

CREATE PROC PROC_CADASTRO
@NOME VARCHAR(30), @SEXO CHAR(1), @NASCIMENTO DATETIME, 
@TIPO CHAR (3), @NUMERO VARCHAR(10)
AS
	DECLARE @FK INT
	
	INSERT INTO TB_PESSOAS VALUES (@NOME, @SEXO, @NASCIMENTO)
	SET @FK = (SELECT IDPESSOA FROM TB_PESSOAS WHERE IDPESSOA = @@IDENTITY)
	
	INSERT INTO TB_TELEFONE VALUES (@TIPO, @NUMERO, @FK)
	PRINT 'CADASTRO FEITO'
GO

PROC_CADASTRO 'JORGE', 'M', '2000/08/12','CEL','8712345951'
GO

SELECT TB_PESSOAS.IDPESSOA, TB_PESSOAS.NOME, TB_PESSOAS.SEXO, TB_PESSOAS.NASCIMENTO,
TB_TELEFONE.TIPO, TB_TELEFONE.NUMERO FROM TB_PESSOAS INNER JOIN TB_TELEFONE 
ON TB_PESSOAS.IDPESSOA = TB_TELEFONE.ID_PESSOA WHERE TB_PESSOAS.IDPESSOA = 4
GO