/*STORED PROCEDURES*/
/*TEMOS QUE ALTERAR O DELIMITADOR! (; PARA $)*/
DELIMITER $

CREATE PROCEDURE FIRMA()
BEGIN
	/** SQL DML*/
	SELECT * FROM CLIENTE ORDER BY IDCLIENTE;
END
$

CALL FIRMA()$
DROP PROCEDURE FIRMA$

/*****************************/
/* PROCEDURES COM PARÂMETROS */

CREATE PROCEDURE CONTA(X INT, Y INT)
BEGIN
	SELECT X+Y AS VALOR;
END
$

CALL CONTA(100,96)$
CALL CONTA(9,5)$
CALL CONTA(-6,90)$
CALL CONTA(2,7)$

/******************************/
CREATE TABLE CURSOS(
	IDCURSO INT AUTO_INCREMENT,
	NOME VARCHAR (25) NOT NULL,
	HORAS INTEGER (3) NOT NULL,
	VALOR INTEGER (10),
	PRIMARY KEY (IDCURSO)
);


CREATE PROCEDURE CAD_CURSO(NULL ,NOME VARCHAR(25), HORAS INTEGER(3), VALOR INTEGER (10,2))
BEGIN

	INSERT INTO CURSOS VALUES(NULL, NOME, HORAS, VALOR);

END$

DELIMITER ;
CALL CAD_CURSO('JAVA',35,279.00);